# Use root/example as user/password credentials
version: '3.8'

services:

  mongo:
    image: mongo:7.0
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 123123

  mongo-express:
    image: mongo-express:1-20
    restart: always
    ports:
      - 8888:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: 123123
      ME_CONFIG_MONGODB_URL: mongodb://root:123123@mongo:27017/
      ME_CONFIG_BASICAUTH: false
