# Use root/example as user/password credentials
version: '3.8'

services:

  mongo:
    image: mongo:7.0
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: dev_only
      MONGO_INITDB_ROOT_PASSWORD: dev_only
